fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: yingz ## `Your` duoshuo_shortname, e.g. haomwei
disqus: ## Your disqus_shortname, e.g. haomwei
google_search: true ## Use Google search, true/false
baidu_search: ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: home
    directory: /
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
#  - page: about
#    directory: about/
#    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - links
  - recent_posts
  - recent_comments

links:
  - title:  Èº‹
    url: http://nap-blog.artemisprojects.org/2015/10/21/books/
#  - title: Artemis Projects
#    url: http://artemisprojects.org/
#  - title: Nanjing Univ.
#    url: http://www.nju.edu.cn/
#  - title: Chun CAO
#    url: http://chun.nemoworks.info/
#  - title: Chenchen CAO
#    url: http://chrisforest.github.io/
  - title: Jie CHEN
    url: http://jetmuffin.github.io/
  - title: Shuo CHEN
    url: http://cshuo.github.io/
  - title: Hongjun GE
    url: http://NAP-GHJ.github.io
# - title:  Huating LIU
#   url: http://hooting.github.io/
  - title: Tianchi LIU
    url: http://itanch.github.io
  - title: Ziling LU
    url: http://Luziling.github.io
  - title: Jing DENG
    url: http://dmemoing.github.io
  - title: Chenglin MENG
    url: http://rdmclin2.github.io/
  - title: Weiyi WANG
    url: http://co2y.github.io/
  - title: Yiqun WANG
    url: http://qunnn41.github.io
  - title: Xiang XU
    url: http://flyxu.github.io
  - title: Zhongliang YUAN
    url: http://monkey-h.github.io/
  - title: Ying ZHANG
    url: http://ying-zhang.github.io/
